apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
  labels:
    app: pacman
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image: ghcr.io/joaoleao7/pacman:2.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pacman
  name: pacman
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: pacman
  type: ClusterIP
status:
  loadBalancer: {}
